// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWebSxjL-DPPCo2g5adqwMmf26vM8uXTc',
    appId: '1:340588707951:web:d60808255b0847b51f8d9a',
    messagingSenderId: '340588707951',
    projectId: 'fir-bloctodo-6a1ee',
    authDomain: 'fir-bloctodo-6a1ee.firebaseapp.com',
    storageBucket: 'fir-bloctodo-6a1ee.appspot.com',
    measurementId: 'G-DZL369Z3Y6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDARsot5DdH_M9Sy3EJm1YL5zIROmcqcKY',
    appId: '1:340588707951:android:d0810bb1b60bf5ac1f8d9a',
    messagingSenderId: '340588707951',
    projectId: 'fir-bloctodo-6a1ee',
    storageBucket: 'fir-bloctodo-6a1ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcHH4AkXOGuTI0lwSsSFInVi1sURkUvfg',
    appId: '1:340588707951:ios:c60674d728a70bb61f8d9a',
    messagingSenderId: '340588707951',
    projectId: 'fir-bloctodo-6a1ee',
    storageBucket: 'fir-bloctodo-6a1ee.appspot.com',
    iosBundleId: 'com.example.todoBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcHH4AkXOGuTI0lwSsSFInVi1sURkUvfg',
    appId: '1:340588707951:ios:d594e0412d3032751f8d9a',
    messagingSenderId: '340588707951',
    projectId: 'fir-bloctodo-6a1ee',
    storageBucket: 'fir-bloctodo-6a1ee.appspot.com',
    iosBundleId: 'com.example.todoBloc.RunnerTests',
  );
}
